# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: "node-exporter"
#     static_configs:
#       - targets: ["node-exporter:9100"]

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["ecommerce-app:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
